Task 3.2
Ritersport/romchirick-android-course pull request #3
Opened 2023-10-30 06:50 UTC by Ritersport

2023-10-31 04:10 UTC, Romchirik requested changes

2023-10-31 04:10 UTC, Romchirik commented on Fragments/app/src/main/java/nsu/leorita/fragments/FragmentA.kt
> +const val tag = "tag"
Давай константы вот так обзывать AWESOME_CONST_NAME, ну и ей нужно дать осмысленное название, а то тег и тег....

2023-10-31 04:10 UTC, Romchirik commented on Fragments/app/src/main/java/nsu/leorita/fragments/FragmentB.kt
> +                replace(R.id.fragmentContainer, FragmentC())
В активити я писал о том, что нужно выносить создание активити в саму активити, к фрагментам это тоже относится

2023-10-31 04:10 UTC, Romchirik commented on Fragments/app/src/main/res/values/style.xml
> +<?xml version="1.0" encoding="utf-8"?>
ЧЕЛ ХАРОШ КОНТЕНТ В КАЙФ, можно почаще вот такого???

2023-10-31 08:33 UTC, Ritersport commented on Fragments/app/src/main/java/nsu/leorita/fragments/FragmentB.kt
> +                replace(R.id.fragmentContainer, FragmentC())
Поправила

2023-10-31 08:33 UTC, Ritersport commented on Fragments/app/src/main/java/nsu/leorita/fragments/FragmentA.kt
> +const val tag = "tag"
Поправила

2023-11-01 06:42 UTC, Romchirik approved these changes

2023-11-01 06:42 UTC, merged