di koin
Ritersport/romchirick-android-course pull request #5
Opened 2023-11-07 18:44 UTC by Ritersport

2023-11-07 18:45 UTC, Ritersport commented
Сори не догадалась коммит без изменений сделать сначала, следующий сделаю

2023-11-11 12:09 UTC, Romchirik requested changes

2023-11-11 12:09 UTC, Romchirik commented on Di-Koin/app/src/main/java/nsu/titov/myconverter/ui/fragments/ConverterFragment.kt
> +    private val viewModel: ConverterViewModel by viewModels()
Поменять на коиновскиий метод

2023-11-11 12:09 UTC, Romchirik commented on Di-Koin/app/src/main/java/nsu/titov/myconverter/presentation/CurrencyListViewModel.kt
> +	private val toaster: Toaster = get()
Нужно убрать коин компонент и сделать инжект через конструктор

2023-11-11 12:09 UTC, Romchirik commented on Di-Koin/app/src/main/java/nsu/titov/myconverter/presentation/CurrencyListViewModel.kt
> +	private val toaster: Toaster = get()
И во второй вьюмодели сделать также

2023-11-19 10:57 UTC, merged